== 线程
系统调度的最小单元，一个进程包含多个线程.

* 栈(Stack)
* 寄存器(Register)
* 本地存储(Thread Local)

== 线程安全
保证共享的、可修改的数据的准确性
* 原子性(同步机制)、可见性(线程修改变量,其状态立马被其他线程知晓,volatile)、有序性(保证串行语义,避免指令重排序)

== 线程状态 Thread.State
* New
* Runnable
* Blocked
* Waiting
* TimedWaiting
* Terminated

== 线程API
* start(): 多次执行将会报错 IllegalThreadStateException
* join()：Waits for this thread to die. 等待线程结束
* yield()：暗示提示调度器当前线程放弃处理器的使用，主动让出CPU
* stop()：废弃过时.该方法是线程不安全的.该方法会释放所有的监视器(monitor),如果原先由monitor保护的对象处于不正确不一致的状态,
损坏的对象变得对其他线程可见,可能导致任意行为.stop替代方法是使用code(通过修改该变量说明目标线程应该停止运行);如果目标线程
长时间等待可以用interrupt()中断等待

== ThreadLocal
保存线程私有信息的机制，在整个线程生命周期内有效。方便在一个线程在不同业务模块中传递信息
如：事务ID,Cookie等上下文信息

== 线程池
=== Executors 提供**5**中不同的线程池
* newCachedThreadPool
```
public static ExecutorService newCachedThreadPool() {
    return new ThreadPoolExecutor(0, Integer.MAX_VALUE,
          60L, TimeUnit.SECONDS,
          new SynchronousQueue<Runnable>());
}
```
* newFixedThreadPool(int nThreads)
```
public static ExecutorService newFixedThreadPool(int nThreads) {
    return new ThreadPoolExecutor(nThreads, nThreads,
          0L, TimeUnit.MILLISECONDS,
          new LinkedBlockingQueue<Runnable>());
}
```
* newSingleThreadExecutor() 工作线程为1，工作队列无界，保证任务顺序执行
```
public static ExecutorService newSingleThreadExecutor() {
    return new FinalizableDelegatedExecutorService
        (new ThreadPoolExecutor(1, 1,
                0L, TimeUnit.MILLISECONDS,
                new LinkedBlockingQueue<Runnable>()));
}
```
* newSingleThreadScheduledExecutor(int corePoolSize) 定时、周期性的工作调度
使用队列 DelayedWorkQueue
```
public static ScheduledExecutorService newSingleThreadScheduledExecutor() {
    return new DelegatedScheduledExecutorService
        (new ScheduledThreadPoolExecutor(corePoolSize));
}
```
* newWorkStealingPool jdk1.8 ForkJoinPool Work-Stealing算法
```
public static ExecutorService newWorkStealingPool(int parallelism) {
    return new ForkJoinPool
        (parallelism,
         ForkJoinPool.defaultForkJoinWorkerThreadFactory,
         null, true);
}
```

=== ThreadPoolExecutor
```
public ThreadPoolExecutor(int corePoolSize,
                              int maximumPoolSize,
                              long keepAliveTime,
                              TimeUnit unit,
                              BlockingQueue<Runnable> workQueue,
                              ThreadFactory threadFactory,
                              RejectedExecutionHandler handler) {
    if (corePoolSize < 0 ||
        maximumPoolSize <= 0 ||
        maximumPoolSize < corePoolSize ||
        keepAliveTime < 0)
        throw new IllegalArgumentException();
    if (workQueue == null || threadFactory == null || handler == null)
        throw new NullPointerException();
    this.acc = System.getSecurityManager() == null ?
            null :
            AccessController.getContext();
    this.corePoolSize = corePoolSize;
    this.maximumPoolSize = maximumPoolSize;
    this.workQueue = workQueue;
    this.keepAliveTime = unit.toNanos(keepAliveTime);
    this.threadFactory = threadFactory;
    this.handler = handler;
}
```