server:
  port: 8001

eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://dev-center-1:8762/eureka/,http://dev-center-2:8763/eureka/ #  locate the Eureka server

spring:
  application:
    name: service-provider